/** YouTube numeric category_id values (legacy / browse taxonomy). */
export const YOUTUBE_CATEGORIES: { id: number; label: string }[] = [
  { id: 1, label: 'Film & Animation' },
  { id: 2, label: 'Autos & Vehicles' },
  { id: 10, label: 'Music' },
  { id: 15, label: 'Pets & Animals' },
  { id: 17, label: 'Sports' },
  { id: 18, label: 'Short Movies' },
  { id: 19, label: 'Travel & Events' },
  { id: 20, label: 'Gaming' },
  { id: 21, label: 'Videoblogging' },
  { id: 22, label: 'People & Blogs' },
  { id: 23, label: 'Comedy' },
  { id: 24, label: 'Entertainment' },
  { id: 25, label: 'News & Politics' },
  { id: 26, label: 'Howto & Style' },
  { id: 27, label: 'Education' },
  { id: 28, label: 'Science & Technology' },
  { id: 29, label: 'Nonprofits & Activism' },
  { id: 30, label: 'Movies' },
  { id: 31, label: 'Anime/Animation' },
  { id: 32, label: 'Action/Adventure' },
  { id: 33, label: 'Classics' },
  { id: 34, label: 'Comedy (movies)' },
  { id: 35, label: 'Documentary' },
  { id: 36, label: 'Drama' },
  { id: 37, label: 'Family' },
  { id: 38, label: 'Foreign' },
  { id: 39, label: 'Horror' },
  { id: 40, label: 'Sci-Fi/Fantasy' },
  { id: 41, label: 'Thriller' },
  { id: 42, label: 'Shorts' },
  { id: 43, label: 'Shows' },
  { id: 44, label: 'Trailers' },
]
